Clean up the find_newer gunk

diff --git a/lib/svc/method/input-method-cache b/lib/svc/method/input-method-cache
--- a/lib/svc/method/input-method-cache
+++ b/lib/svc/method/input-method-cache
@@ -1,6 +1,7 @@
 #!/bin/ksh -p
 #
 # Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
+# Copyright 2012-2016 Peter C. Tribble
 # Use is subject to license terms.
 #
 # Permission is hereby granted, free of charge, to any person obtaining a
@@ -36,7 +37,6 @@ PATH=/usr/bin:/usr/sbin
 . /lib/svc/share/smf_include.sh
 
 USAGE="Usage: $0 { start | refresh }"
-FIND_NEWER=/usr/share/desktop-cache/find_newer
 
 if [ $# -ne 1 ] ; then
     echo $USAGE
@@ -60,59 +60,21 @@ if [[ $ARCH64 != "amd64" ]] && [[ "$ARCH64" != "sparcv9" ]]; then
   ARCH64=""
 fi
 
-start_input_method_cache ()
+do_input_method_cache ()
 {
 for DIR in "" $ARCH64; do
   test -x /usr/bin/$DIR/gtk-query-immodules-2.0 || {
       echo "gtk-query-immodules-2.0 not installed"
       continue
   }
-  if [ -a "/usr/etc/$DIR/gtk-2.0/gtk.immodules" ]; then
-    RESULT=`${FIND_NEWER} -c -f -m --name '*.so' \
-	--newer /usr/etc/$DIR/gtk-2.0/gtk.immodules \
-	/usr/lib/$DIR/gtk-2.0/*/immodules 2>/dev/null`
-  else
-    RESULT="no cache file"
-  fi
-
-  if [ -n "$RESULT" ]; then 
-    echo "updating/creating im modules cache file"
-    /usr/bin/$DIR/gtk-query-immodules-2.0 /usr/lib/$DIR/gtk-2.0/*/immodules/*.so \
+  echo "updating/creating im modules cache file"
+  /usr/bin/$DIR/gtk-query-immodules-2.0 /usr/lib/$DIR/gtk-2.0/*/immodules/*.so \
 	> /usr/etc/$DIR/gtk-2.0/gtk.immodules
-    if [ $? -ne 0 ]; then
-      echo "gtk-query-immodules-2.0 exited with an error while generating the cache file /usr/etc/$DIR/gtk-2.0/gtk.immodules"
-      exit $SMF_EXIT_ERR_FATAL
-    else
-      echo "input method cache installed in /usr/etc/$DIR/gtk-2.0/gtk.immodules"
-    fi
-  fi
-done
-}
-
-refresh_input_method_cache ()
-{
-for DIR in "" $ARCH64; do
-  test -x /usr/bin/$DIR/gtk-query-immodules-2.0 || {
-      echo "gtk-query-immodules-2.0 not installed"
-      continue
-  }
-  if [ -a "/usr/etc/$DIR/gtk-2.0/gtk.immodules" ]; then
-    RESULT=`/usr/bin/find /usr/lib/$DIR/gtk-2.0/*/immodules/*.so ! -type d \
-	    -follow 2>/dev/null`
+  if [ $? -ne 0 ]; then
+    echo "gtk-query-immodules-2.0 exited with an error while generating the cache file /usr/etc/$DIR/gtk-2.0/gtk.immodules"
+    exit $SMF_EXIT_ERR_FATAL
   else
-    RESULT="no cache file"
-  fi
-
-  if [ -n "$RESULT" ]; then 
-    echo "updating/creating im modules cache file"
-    /usr/bin/$DIR/gtk-query-immodules-2.0 /usr/lib/$DIR/gtk-2.0/*/immodules/*.so \
-	> /usr/etc/$DIR/gtk-2.0/gtk.immodules
-    if [ $? -ne 0 ]; then
-      echo "gtk-query-immodules-2.0 exited with an error while generating the cache file /usr/etc/$DIR/gtk-2.0/gtk.immodules"
-      exit $SMF_EXIT_ERR_FATAL
-    else
-      echo "input method cache installed in /usr/etc/$DIR/gtk-2.0/gtk.immodules"
-    fi
+    echo "input method cache installed in /usr/etc/$DIR/gtk-2.0/gtk.immodules"
   fi
 done
 }
@@ -136,6 +98,6 @@ case "$METHOD" in
 	;;
 esac
 
-${METHOD}_input_method_cache
+do_input_method_cache
 
 exit $SMF_EXIT_OK
